FROM ubuntu:trusty

RUN apt-get update && apt-get install -y \
    net-tools \
    iputils-ping \
    iproute2 \
    telnet telnetd \
    iperf \
    tcpdump \
    iperf3 \
    traceroute

CMD /bin/bash